### ISSUE TITLE
[1.7.10] Add Support for TerraFirmaCraftPlus

### ISSUE THREAD

**Issue by LeDemmers** [Andrew2070/Empires-Mod#12]
[1] Name: Corey
[2] Discord: DEMMERS#0001
[3] Description: Need a protections file added to the mod for 1.7.10 TFC+ made by Dunk.
https://www.curseforge.com/minecraft/mc-mods/terrafirmacraftplus

**Comment by Paralaxus** [comment]
Hello Corey,

1.7.10 is no longer supported as i do not have the time.

Check out MyTown2's support page for developing your own protection files. They are quick and easy JSON files, or take a look at the protection files for an example on how to make one.

The 1.12.2 version will most likely use a more automated method.
